spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

jwt:
  secret:

app:
  auth:
    token-secret:
#    token-expiry: 86400000 # 24시간
    token-expiry: 60000 # 1분
    refresh-token-expiry: 1209600000 # 7일

saml:
  ssafy:
    verification-key-path:
    entity-id:
    service-location: