spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

jwt:
  secret:

app:
  auth:
    token-secret:
    token-expiry: 86400000 # 24시간
    #    token-expiry: 10000 # 10초
    refresh-token-expiry: 1209600000 # 7일